name: game_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 2.0.2+5


environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

 
  cupertino_icons: ^1.0.8
  firebase_core: ^4.0.0
  google_fonts:  6.3.0 
  equatable: ^2.0.7
  firebase_auth: 6.0.1
  
  flutter_bloc: ^9.1.1
  flutter_staggered_animations: ^1.1.1
  intl: ^0.20.2
  lottie: ^3.3.1
  
  fluttertoast: ^8.2.12
  toastification: ^3.0.3
  bloc: ^9.0.0
  provider: 6.1.5+1
  geolocator: 14.0.2
  geocoding: ^4.0.0
  image_picker: 1.2.0 
  firebase_storage: ^13.0.0
  permission_handler: 12.0.1
  flutter_typeahead: ^5.2.0
  shimmer: ^3.0.0
  flutter_svg: ^2.1.0
  flutter_native_splash: 2.4.6
  bcrypt: ^1.1.3
  animation_list: ^3.1.0
  firebase_app_check: ^0.4.0
  cloud_firestore:  6.0.0 
  badges: ^3.1.2
  cached_network_image: ^3.4.1
  shared_preferences: ^2.5.3
  timezone: ^0.10.1
  country_code_picker:  3.4.0  
  rxdart: ^0.28.0
  percent_indicator: ^4.2.5
  iconsax: ^0.0.8
  uuid: ^4.5.1
  image_cropper: ^9.1.0
  http: ^1.5.0
  flutter_dotenv: ^6.0.0
  flutter_screenutil: ^5.9.3
  connectivity_plus: ^7.0.0
  path: ^1.9.1
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: 0.14.4  
  flutter_lints:  6.0.0


flutter:

  uses-material-design: true

  assets:
    
    - assets/lottie/splash_animation.json
    - assets/logo.png
    - assets/sketch1.jpg
    - assets/sketch2.jpeg
    - assets/sketch3.jpeg
    - assets/sketch4.jpeg
    - assets/match.jpeg
    - assets/court.jpeg
    - assets/tournament.jpeg
    - assets/tournament_placholder.jpg
    - assets/5981383.png
    - assets/app_logo.png
    - assets/open.png
    - .env
   

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/5981383.png"