// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPKl7Um23KOMXv1vNUlYdIkELRjUcRY58',
    appId: '1:427126638951:web:502d94fa05d2d9d3ca47c2',
    messagingSenderId: '427126638951',
    projectId: 'game-39b8e',
    authDomain: 'game-39b8e.firebaseapp.com',
    storageBucket: 'game-39b8e.firebasestorage.app',
    measurementId: 'G-3E70B016BT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMPRkvSHRjQSxOirhf2Az0KZuFdtZfB5U',
    appId: '1:427126638951:android:214e44314b795138ca47c2',
    messagingSenderId: '427126638951',
    projectId: 'game-39b8e',
    storageBucket: 'game-39b8e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhniRtOrOxwYdI-cAqRsf6KF1GUSH0O3U',
    appId: '1:427126638951:ios:5afcf6b7a3a11f04ca47c2',
    messagingSenderId: '427126638951',
    projectId: 'game-39b8e',
    storageBucket: 'game-39b8e.firebasestorage.app',
    androidClientId: '427126638951-n7kagd2jue1da2hoq0q2l9h2ml0bf5vk.apps.googleusercontent.com',
    iosClientId: '427126638951-qpgrpu4f76jg8u9lsk6o464osb6ft7gm.apps.googleusercontent.com',
    iosBundleId: 'com.example.gameApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhniRtOrOxwYdI-cAqRsf6KF1GUSH0O3U',
    appId: '1:427126638951:ios:5afcf6b7a3a11f04ca47c2',
    messagingSenderId: '427126638951',
    projectId: 'game-39b8e',
    storageBucket: 'game-39b8e.firebasestorage.app',
    androidClientId: '427126638951-n7kagd2jue1da2hoq0q2l9h2ml0bf5vk.apps.googleusercontent.com',
    iosClientId: '427126638951-qpgrpu4f76jg8u9lsk6o464osb6ft7gm.apps.googleusercontent.com',
    iosBundleId: 'com.example.gameApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBPKl7Um23KOMXv1vNUlYdIkELRjUcRY58',
    appId: '1:427126638951:web:502d94fa05d2d9d3ca47c2',
    messagingSenderId: '427126638951',
    projectId: 'game-39b8e',
    authDomain: 'game-39b8e.firebaseapp.com',
    storageBucket: 'game-39b8e.firebasestorage.app',
    measurementId: 'G-3E70B016BT',
  );

}